name: adb_connect
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.11
  freezed_annotation: ^0.15.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  macos_ui: ^0.10.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  mocktail: ^0.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/devices-lineup.png
  fonts:
    - family:  AdbConnectIcons
      fonts:
        - asset: assets/icons/AdbConnectIcons.ttf
